# Ing_JQC: Configuración SMTP Gmail

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jonathanq1985@gmail.com
spring.mail.password=13deoctubre@@

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true